# Generated by Django 3.2 on 2023-05-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_purpose', models.CharField(choices=[('', 'Purpose of Inquiry'), ('PRODUCT', 'Poduct Inquiry'), ('ORDER', 'Order Inquiry'), ('SUGGESTIONS', 'Suggestions'), ('OTHER', 'Other')], max_length=24)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('date_submmited', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_submmited'],
            },
        ),
    ]
