# Generated by Django 3.2 on 2023-06-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inquiry_purpose',
            field=models.CharField(choices=[('', 'Purpose of Inquiry'), ('PRODUCT', 'Product Inquiry'), ('ORDER', 'Order Inquiry'), ('SUGGESTIONS', 'Suggestions'), ('OTHER', 'Other')], max_length=24),
        ),
    ]
